defaults:

# Alfresco Content Services
  - scope:
      path: "content-services"
    values:
      layout: "docs"
      product: "Alfresco Content Services"
      toc: "content-services"
      versions:
        - 6.2
        - 6.1
        - 6.0
        - 5.2
  - scope:
      path: "content-services/latest"
    values:
      version: 6.2
      latest: true
  - scope:
      path: "content-services/6.1"
    values:
      version: 6.1
  - scope:
      path: "content-services/6.0"
    values:
      version: 6.0
  - scope:
      path: "content-services/5.2"
    values:
      version: 5.2
  - scope:
      path: "content-services/community"
    values:
      version: "Community"

# Alfresco Google Drive
  - scope:
      path: "google-drive"
    values:
      layout: "docs"
      product: "Alfresco Google Docs Integration"
      location: "google-drive"
      toc: "google-drive"
      support: true
      versions:
        - 3.2
        - 3.1
  - scope:
      path: "google-drive/latest"
    values:
      version: 3.2
      latest: true
  - scope:
      path: "google-drive/3.1"
    values:
      version: 3.1

# Alfresco Content Connector for Azure
  - scope:
      path: "microsoft-azure"
    values:
      layout: "docs"
      product: "Alfresco Content Connector for Azure"
      location: "microsoft-azure"
      toc: "microsoft-azure"
      support: true
      versions:
        - 1.1
        - 1.0
  - scope:
      path: "microsoft-azure/latest"
    values:
      version: 1.1
      latest: true
  - scope:
      path: "microsoft-azure/1.0"
    values:
      version: 1.0

# Alfresco Identity Service
  - scope:
      path: "identity-service"
    values:
      layout: "docs"
      product: "Alfresco Identity Service"
      location: "identity-service"
      toc: "identity-service"
      support: true
      versions:
        - 1.3
        - 1.2
        - 1.1
        - 1.0
  - scope:
      path: "identity-service/latest"
    values:
      version: 1.3
      latest: true
  - scope:
      path: "identity-service/1.2"
    values:
      version: 1.2
  - scope:
      path: "identity-service/1.1"
    values:
      version: 1.1
  - scope:
      path: "identity-service/1.0"
    values:
      version: 1.0

# Alfresco Document Transformation Engine
  - scope:
      path: "transformation-engine"
    values:
      layout: "docs"
      product: "Alfresco Document Transformation Engine"
      location: "transformation-engine"
      toc: "transformation-engine"
      support: true
      versions:
        - 2.2
  - scope:
      path: "transformation-engine/latest"
    values:
      version: 2.2
      latest: true

# Alfresco Media Management
  - scope:
      path: "media-management"
    values:
      layout: "docs"
      product: "Alfresco Media Management"
      location: "media-management"
      toc: "media-management"
      support: true
      versions:
        - 1.4
        - 1.3
  - scope:
      path: "media-management/latest"
    values:
      version: 1.4
      latest: true
  - scope:
      path: "media-management/1.3"
    values:
      version: 1.3

  - scope:
      path: "activiti"
    values:
      layout: "docs"
      product: "Alfresco Activiti Enterprise"
      toc: "activiti"
      versions:
        - 7.1.0-M8
        - 7.1.0-M7
        - 7.1.0-M6
        - 7.1.0-M5
      audiences:
        - "admin"
        - "developer"
        - "user"
  - scope:
      path: "activiti/latest"
    values:
      version: 7.1.0-M8
      latest: true
  - scope:
      path: "activiti/latest/admin"
    values:
      audience: "admin"
  - scope:
      path: "activiti/latest/user"
    values:
      audience: "user"
  - scope:
      path: "activiti/latest/developer"
    values:
      audience: "developer"

sass:
  sass_dir: assets/include/scss
permalink: pretty

git-repo: https://github.com/Alfresco/docs-alfresco/edit/master

kramdown:
  input: GFM
  auto_ids: true

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - searchyll

highlighter: none

elasticsearch:
  url: https://search-docs-dev-kcq7soqflyxmts7m3a3prekrzi.us-east-1.es.amazonaws.com
  index_name: sandbox

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .github/
  - README.md
  - CODEOWNERS
  - .gitignore
  # - .sass-cache/
  - .jekyll-cache/
  # - gemfiles/
  - Gemfile
  - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
