# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

defaults:
  # ALFRESCO SYNC SERVICE

  - scope:
      path: "activiti"
    values:
      layout: "docs"
      product: "Alfresco Activiti Enterprise"
      location: "activiti"
      versions:
        - 7.1.0-M8
        - 7.1.0-M7
        - 7.1.0-M6
        - 7.1.0-M5
      audiences:
        - "admin"
        - "developer"
        - "user"
  - scope:
      path: "activiti/latest"
    values:
      version: 7.1.0-M8
      latest: true
  - scope:
      path: "activiti/latest/admin"
    values:
      audience: "admin"
  - scope:
      path: "activiti/latest/user"
    values:
      audience: "user"
  - scope:
      path: "activiti/latest/developer"
    values:
      audience: "developer"

sass:
  sass_dir: assets/include/scss
permalink: pretty

git-repo: https://github.com/Alfresco/docs-alfresco/edit/master

kramdown:
  input: GFM
  auto_ids: true

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - searchyll

highlighter: none

elasticsearch:
  url: https://search-test-dev-es-pxmeiqsie66va47wsko6p2q3jm.us-east-1.es.amazonaws.com
  index_name: default

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .github/
  - README.md
  - .gitignore
  # - .sass-cache/
  - .jekyll-cache/
  # - gemfiles/
  - Gemfile
  - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
