defaults:

# Alfresco Content Services
  - scope:
      path: "content-services"
    values:
      layout: "docs"
      product: "Alfresco Content Services"
      toc: "content-services"
      location: "content-services"
      tutorial: true
      support: true
      versions:
        - 6.2
        - 6.1
        - 6.0
        - 5.2
  - scope:
      path: "content-services/latest"
    values:
      version: 6.2
      latest: true
  - scope:
      path: "content-services/latest/tutorial"
    values:
      toc: "content-services-tutorial"
  - scope:
      path: "content-services/6.1"
    values:
      version: 6.1
  - scope:
      path: "content-services/6.0"
    values:
      version: 6.0
  - scope:
      path: "content-services/5.2"
    values:
      version: 5.2
  - scope:
      path: "content-services/community"
    values:
      version: "Community"

# Alfresco Digital Workspace
  - scope:
      path: "digital-workspace"
    values:
      layout: "docs"
      product: "Alfresco Digital Workspace"
      location: "digital-workspace"
      toc: "digital-workspace"
      support: true
      versions:
        - 2.0
        - 1.6
        - 1.5
  - scope:
      path: "digital-workspace/latest"
    values:
      version: 2.0
      latest: true
  - scope:
      path: "digital-workspace/1.6"
    values:
      version: 1.6 
  - scope:
      path: "digital-workspace/1.5"
    values:
      version: 1.5

# Alfresco Google Drive
  - scope:
      path: "google-drive"
    values:
      layout: "docs"
      product: "Alfresco Google Docs Integration"
      location: "google-drive"
      toc: "google-drive"
      support: true
      versions:
        - 3.2
        - 3.1
  - scope:
      path: "google-drive/latest"
    values:
      version: 3.2
      latest: true
  - scope:
      path: "google-drive/3.1"
    values:
      version: 3.1

# Alfresco Content Connector for AWS Glacier
  - scope:
      path: "aws-glacier"
    values:
      layout: "docs"
      product: "Alfresco Content Connector for AWS Glacier"
      location: "aws-glacier"
      toc: "aws-glacier"
      support: true
      versions:
        - 2.1
        - 2.0
        - 1.0
  - scope:
      path: "aws-glacier/latest"
    values:
      version: 2.1
      latest: true
  - scope:
      path: "aws-glacier/2.0"
    values:
      version: 2.0
  - scope:    
      path: "aws-glacier/1.0"
    values:
      version: 1.0
      
# Alfresco Content Connector for Azure
  - scope:
      path: "microsoft-azure"
    values:
      layout: "docs"
      product: "Alfresco Content Connector for Azure"
      location: "microsoft-azure"
      toc: "microsoft-azure"
      support: true
      versions:
        - 1.1
        - 1.0
  - scope:
      path: "microsoft-azure/latest"
    values:
      version: 1.1
      latest: true
  - scope:
      path: "microsoft-azure/1.0"
    values:
      version: 1.0

# Alfresco Content Connector for Salesforce
  - scope:
      path: "salesforce"
    values:
      layout: "docs"
      product: "Alfresco Content Connector for Salesforce"
      location: "salesforce"
      toc: "salesforce"
      support: true
      versions:
        - 2.2
        - 2.1
  - scope:
      path: "salesforce/latest"
    values:
      version: 2.2
      latest: true
  - scope:
      path: "salesforce/2.1"
    values:
      version: 2.1

# Alfresco Identity Service
  - scope:
      path: "identity-service"
    values:
      layout: "docs"
      product: "Alfresco Identity Service"
      location: "identity-service"
      toc: "identity-service"
      support: true
      tutorial: true
      versions:
        - 1.3
        - 1.2
        - 1.1
        - 1.0
  - scope:
      path: "identity-service/latest"
    values:
      version: 1.3
      latest: true
  - scope:
      path: "identity-service/latest/tutorial"
    values:
      toc: "identity-service-tutorial"
  - scope:
      path: "identity-service/1.2"
    values:
      version: 1.2
  - scope:
      path: "identity-service/1.2/tutorial"
    values:
      toc: "identity-service-tutorial"
  - scope:
      path: "identity-service/1.1"
    values:
      version: 1.1
  - scope:
      path: "identity-service/1.1/tutorial"
    values:
      toc: "identity-service-tutorial"
  - scope:
      path: "identity-service/1.0"
    values:
      version: 1.0
      tutorial: false

# Alfresco Desktop Sync
  - scope:
      path: "desktop-sync"
    values:
      layout: "docs"
      product: "Alfresco Desktop Sync"
      location: "desktop-sync"
      toc: "desktop-sync"
      support: true
      versions:
        - 1.6
        - 1.5
  - scope:
      path: "desktop-sync/latest"
    values:
      version: 1.6
      latest: true
  - scope:
      path: "desktop-sync/1.5"
    values:
      version: 1.5

# Alfresco Governance Services
  - scope:
      path: "governance-services"
    values:
      layout: "docs"
      product: "Alfresco Governance Services"
      location: "governance-services"
      toc: "governance-services"
      tutorial: true
      support: true
      versions:
        - 3.4
        - 3.3
  - scope:
      path: "governance-services/latest"
    values:
      version: 3.4
      latest: true
  - scope:
      path: "governance-services/latest/tutorial"
    values:
      toc: "governance-services-tutorial"
  - scope:
      path: "governance-services/3.3"
    values:
      version: 3.3
  - scope:
      path: "governance-services/3.3/tutorial"
    values:
      toc: "governance-services-tutorial"

# Alfresco Process Services (APS)
  - scope:
      path: "process-services"
    values:
      layout: "docs"
      product: "Alfresco Process Services"
      location: "process-services"
      toc: "process-services"
      support: true
      versions:
        - 1.11
        - "1.10"
        - 1.9
  - scope:
      path: "process-services/latest"
    values:
      version: 1.11
      latest: true
  - scope:
      path: "process-services/1.10"
    values:
      version: "1.10"
  - scope:
      path: "process-services/1.9"
    values:
      version: 1.9

# Alfresco Document Transformation Engine
  - scope:
      path: "transformation-engine"
    values:
      layout: "docs"
      product: "Alfresco Document Transformation Engine"
      location: "transformation-engine"
      toc: "transformation-engine"
      support: true
      versions:
        - 2.2
  - scope:
      path: "transformation-engine/latest"
    values:
      version: 2.2
      latest: true

# Alfresco Content Connector for AWS S3
  - scope:
      path: "aws-s3"
    values:
      layout: "docs"
      product: "Alfresco Content Connector for AWS S3"
      location: "aws-s3"
      toc: "aws-s3"
      support: true
      versions:
        - 3.1
  - scope:
      path: "aws-s3/latest"
    values:
      version: 3.1
      latest: true

# Alfresco Office Services
  - scope:
      path: "microsoft-office"
    values:
      layout: "docs"
      product: "Alfresco Office Services"
      location: "microsoft-office"
      toc: "microsoft-office"
      support: true
      versions:
        - 1.3
        - 1.2
        - 1.1
  - scope:
      path: "microsoft-office/latest"
    values:
      version: 1.3
      latest: true
  - scope:
      path: "microsoft-office/1.2"
    values:
      version: 1.2
  - scope:
      path: "microsoft-office/1.1"
    values:
      version: 1.1

# Alfresco Transform Service
  - scope:
      path: "transform-service"
    values:
      layout: "docs"
      product: "Alfresco Transform Service"
      location: "transform-service"
      toc: "transform-service"
      support: true
      versions:
        - 1.3
        - 1.2
  - scope:
      path: "transform-service/latest"
    values:
      version: 1.3
      latest: true
  - scope:
      path: "transform-service/1.2"
    values:
      version: 1.2

 # Alfresco Media Management
  - scope:
      path: "media-management"
    values:
      layout: "docs"
      product: "Alfresco Media Management"
      location: "media-management"
      toc: "media-management"
      tutorial: true
      support: true
      versions:
        - 1.4
        - 1.3
        - 1.2
  - scope:
      path: "media-management/latest"
    values:
      version: 1.4
      latest: true
  - scope:
      path: "media-management/latest/tutorial"
    values:
      toc: "media-management-tutorial"
  - scope:
      path: "media-management/1.3"
    values:
      version: 1.3
  - scope:
      path: "media-management/1.3/tutorial"
    values:
      toc: "media-management-tutorial"
  - scope:
      path: "media-management/1.2"
    values:
      version: 1.2
  - scope:
      path: "media-management/1.2/tutorial"
    values:
      toc: "media-management-tutorial"

# SAML Module for Alfresco Content Services
  - scope:
      path: "saml-module"
    values:
      layout: "docs"
      product: "SAML Module for Alfresco Content Services"
      location: "saml-module"
      toc: "saml-module"
      support: true
      versions:
        - 1.2
        - 1.1
  - scope:
      path: "saml-module/latest"
    values:
      version: 1.2
      latest: true
  - scope:
      path: "saml-module/1.1"
    values:
      version: 1.1

# Alfresco Content Connector for SAP Applications
  - scope:
      path: "sap"
    values:
      layout: "docs"
      product: "Alfresco Content Connector for SAP Applications"
      location: "sap"
      toc: "sap"
      support: true
      versions:
        - 5.0
  - scope:
      path: "sap/latest"
    values:
      version: 5.0
      latest: true

# Alfresco ECM Centera
  - scope:
      path: "centera"
    values:
      layout: "docs"
      product: "Alfresco Content Connector for EMC Centera"
      location: "centera"
      toc: "centera"
      support: true
      versions:
        - 2.2
  - scope:
      path: "centera/latest"
    values:
      version: 2.2
      latest: true

# Alfresco Process Automation
  - scope:
      path: "process-automation"
    values:
      layout: "docs"
      product: "Alfresco Process Automation"
      location: "process-automation"
      toc: "process-automation"
  - scope:
      path: "process-automation/latest"
    values:
      version: 1.0
      latest: true


# Alfresco Federation Services
  - scope:
      path: "federation-services"
    values:
      layout: "docs"
      product: "Alfresco Federation Services"
      location: "federation-services"
      toc: "federation-services"
      support: true
      versions:
        - 1.0
  - scope:
      path: "federation-services/latest"
    values:
      version: 1.0
      latest: true

# Alfresco Search and Insight Engine
  - scope:
      path: "insight-engine"
    values:
      layout: "docs"
      product: "Alfresco Search and Insight Engine"
      location: "insight-engine"
      toc: "insight-engine"
      support: true
      versions:
        - 2.0
        - 1.4
  - scope:
      path: "insight-engine/latest"
    values:
      version: 2.0
      latest: true
  - scope:
      path: "insight-engine/1.4"
    values:
      version: 1.4

# Alfresco Search Services
  - scope:
      path: "search-services"
    values:
      layout: "docs"
      product: "Alfresco Search Services"
      location: "search-services"
      toc: "search-services"
      support: true
      versions:
        - 2.0
        - 1.4
        - 1.3
  - scope:
      path: "search-services/latest"
    values:
      version: 2.0
      latest: true
  - scope:
      path: "search-services/1.4"
    values:
      version: 1.4
  - scope:
      path: "search-services/1.3"
    values:
      version: 1.3

# Alfresco Sync Service
  - scope:
      path: "sync-service"
    values:
      layout: "docs"
      product: "Alfresco Sync Service"
      location: "sync-service"
      toc: "sync-service"
      support: true
      versions:
        - 3.3
        - 3.2
        - 3.1
        - 3.0
  - scope:
      path: "sync-service/latest"
    values:
      version: 3.3
      latest: true
  - scope:
      path: "sync-service/3.2"
    values:
      version: 3.2
  - scope:
      path: "sync-service/3.1"
    values:
      version: 3.1
  - scope:
      path: "sync-service/3.0"
    values:
      version: 3.0

# Alfresco Intelligence Services
  - scope:
      path: "intelligence-services"
    values:
      layout: "docs"
      product: "Alfresco Intelligence Services"
      location: "intelligence-services"
      toc: "intelligence-services"
      support: true
      versions:
        - 1.2
        - 1.1
        - 1.0
  - scope:
      path: "intelligence-services/latest"
    values:
      version: 1.2
      latest: true
  - scope:
      path: "intelligence-services/1.1"
    values:
      version: 1.1
  - scope:
      path: "intelligence-services/1.0"
    values:
      version: 1.0

# Alfresco Support Handbook
  - scope:
      path: "support"
    values:
      layout: "docs"
      product: "Alfresco Support Handbook"
      location: "support"
      toc: "support"
  - scope:
      path: "support/latest"
    values:
      version: 1.0
      latest: true

# Alfresco Outlook Integration
  - scope:
      path: "microsoft-outlook"
    values:
      layout: "docs"
      product: "Alfresco Outlook Integration"
      location: "microsoft-outlook"
      toc: "microsoft-outlook"
      support: true
      versions:
        - 2.7
        - 2.6
        - 2.5
        - 2.4
  - scope:
      path: "microsoft-outlook/latest"
    values:
      version: 2.7
      latest: true
  - scope:
      path: "microsoft-outlook/2.6"
    values:
      version: 2.6
  - scope:
      path: "microsoft-outlook/2.5"
    values:
      version: 2.5
  - scope:
      path: "microsoft-outlook/2.4"
    values:
      version: 2.4

# Alfresco Content Services for Mobile
  - scope:
      path: "content-mobile"
    values:
      layout: "docs"
      product: "Alfresco Content Services for Mobile"
      location: "content-mobile"
      toc: "content-mobile"
  - scope:
      path: "content-mobile/latest"
    values:
      version: 1.0
      latest: true


sass:
  sass_dir: assets/include/scss
permalink: pretty

git-repo: https://github.com/Alfresco/docs-alfresco/edit/master

kramdown:
  input: GFM
  auto_ids: true

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - searchyll

highlighter: none

# Elasticsearch/Searchyll settings
elasticsearch:
  url: https://search-docs-dev-kcq7soqflyxmts7m3a3prekrzi.us-east-1.es.amazonaws.com
  index_name: sandbox

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - redirects/
  - .github/
  - README.md
  - README.markdown
  - Dockerfile
  - docker-compose.yml
  - .gitignore
  # - .sass-cache/
  - .jekyll-cache/
  # - gemfiles/
  - Gemfile
  - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
