name: Sandbox

on:
  push:
    branches-ignore:
      - master

env:
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_NAME: ${{ secrets.SANDBOX_BUCKET_NAME }}
  DISTRIBUTION_ID: ${{ secrets.SANDBOX_DISTRIBUTION_ID }}
  RUNNER_ROLE: ${{ secrets.EAD_PRODUCTION_RUNNER_ROLE }}
  RUNNER_EXTERNAL_ID: ${{ secrets.EAD_PROD_RUNNER_EXTERNAL_ID }}

jobs:
  Publish:
    
    runs-on: ubuntu-latest

    if: ${{ github.repository }} == 'Alfresco/docs-alfresco'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        # provide access to SSH user that triggered the build
        limit-access-to-actor: true

    - name: AWS Assume Role
      uses: ./.github/actions/assume_role

    - name: Run Jekyll Build
      uses: ./.github/actions/jekyll_build
      env:
        JEKYLL_CONFIG: _config.yml

    - name: Run S3 Sync
      uses: ./.github/actions/s3_sync
      